# Generated by Django 5.0.1 on 2024-01-22 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_rename_like_likepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 7, 55, 21, 843080)),
        ),
        migrations.AddField(
            model_name='likepost',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 7, 55, 21, 843086)),
        ),
    ]
