# Generated by Django 5.0.1 on 2024-01-22 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0008_alter_likepost_created_at_alter_likepost_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 9, 55, 25, 208647)),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 9, 55, 25, 208654)),
        ),
    ]
