# Generated by Django 5.0.1 on 2024-01-22 09:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 22, 9, 55, 25, 209758))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 1, 22, 9, 55, 25, 209764))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
