# Generated by Django 5.0.1 on 2024-01-22 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likesComment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 8, 28, 29, 458024)),
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 8, 28, 29, 458030)),
        ),
    ]
