# Generated by Django 5.0.1 on 2024-01-22 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likesComment', '0004_alter_likecomment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 8, 49, 36, 42846)),
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 8, 49, 36, 42851)),
        ),
    ]
