# Generated by Django 5.0.1 on 2024-01-19 09:50

import datetime
import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_to)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 19, 9, 50, 59, 515324))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 1, 19, 9, 50, 59, 515337))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
