# Generated by Django 5.0.1 on 2024-01-19 10:01

import datetime
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_category_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 10, 1, 36, 130369)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 10, 1, 36, 130381)),
        ),
    ]
