# Generated by Django 5.0.1 on 2024-01-20 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_created_at_alter_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('beauty', 'Beauty'), ('travel', 'Travel'), ('lifestyle', 'Lifestyle'), ('personal', 'Personal'), ('tech', 'Tech'), ('health', 'Health'), ('fitness', 'Fitness'), ('wellness', 'Wellness')], default='fashion', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 20, 8, 26, 18, 131715)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 20, 8, 26, 18, 131727)),
        ),
    ]
