# Generated by Django 5.0.1 on 2024-01-22 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0013_alter_comment_created_at_alter_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 8, 47, 44, 283776)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 8, 47, 44, 283783)),
        ),
    ]
