# Generated by Django 5.0.1 on 2024-01-26 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0016_alter_comment_created_at_alter_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 4, 59, 21, 140359)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 4, 59, 21, 140365)),
        ),
    ]
